apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-docs-app
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-docs-app
  uid: dccecbef-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '8863784'
  generation: 156
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-docs-app
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-docs-app:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-docs-app@sha256:1bdb44f5421216c633e207dd427b4c0d26ae3e21a78bd05bd673e900e02d5a1c
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-docs-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-docs-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: omar-docs-app
          image: >-
            172.30.181.173:5000/o2/omar-docs-app@sha256:1bdb44f5421216c633e207dd427b4c0d26ae3e21a78bd05bd673e900e02d5a1c
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          resources: {}
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 152
  observedGeneration: 156
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-docs-app:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-10-31T18:15:52Z'
      lastTransitionTime: '2017-10-31T18:15:52Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-11-30T12:34:23Z'
      lastTransitionTime: '2017-11-30T12:34:21Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-docs-app-152" successfully rolled out
  readyReplicas: 1
